apiVersion: v1
kind: Service
metadata:
  name: my-ciquickstart-svc
  labels:
    app: ciquickstart
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ciquickstart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ciquickstart
  labels:
    app: ciquickstart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ciquickstart
  template:
    metadata:
      labels:
        app: ciquickstart
    spec:
      containers:
      - name: ciquickstart
        image: rishald/ciquickstart:15
        ports:
        - containerPort: 80